version: '3'
services:
  relay:
    image: "marisn/elmtool:latest"
    container_name: elmtool
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./config.ini:/etc/elmtool/config.ini
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"