#需要把没用的cookie配置删除
#exchange 是否开启饿了么10元优惠券兑换
#cron 定时任务 参考：https://tool.lu/crontab/
#notification 是否开启消息通知 可选参数 false / true
#notice_system 消息通知类型 可选参数 TgBot / ServerChan 后续将添加更多类型 请关注版本更新
auth: "授权码"
exchange: false
cron: 59 9,18 * * *
cookies:
    - "这里替换cookie"
    - "多个cookie"
    - "多个cookie"
notification: false
notice_system: "TgBot"
TgBot:
    ## 下方填写自己申请@BotFather的Token，如10xxx4:AAFcqxxxxgER5uw
    TG_BOT_TOKEN: ""
    ## 下方填写 @getuseridbot 中获取到的纯数字ID
    TG_USER_ID: ""
    ## 下方填写代理URL，代理类型为 http，比如 http://127.0.0.1:1080
    TG_PROXY_URL: ""
    ## Telegram api自建反向代理地址（选填）
    ## 教程：https://www.hostloc.com/thread-805441-1-1.html
    ## 如反向代理地址 需要填写完整协议 如 http://aaa.bbb.ccc
    ## 为空则不使用反向代理 国内推荐反代通知
    TG_API_HOST: ""
ServerChan:
    ## Server酱
    ## https://sct.ftqq.com
    ## 下方填写 SCHKEY 值或 SendKey 值
    PUSH_KEY: ""